clinicaPsico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appointment.urls')),
    path('', include('core.urls')),
    path('', include('emailmarketing.urls')),
    path('pages/', include('pages.urls')),
    path('', include('patients.urls')),
    path('', include('professionals.urls')),
    path('', include('specialtys.urls')),
    path('', include('workshops.urls')),
    # paths de Auth. con este path django nos provee de varias urls para manejar autenticacion
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),    
    path('summernote/', include('django_summernote.urls')),
    
]
if settings.DEBUG:
    from django.conf.urls.static import static
    # variables MEDIA_URL Y MEDIA_ROOT las tenemos que declarar en el settings del proyecto
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomePageView, AboutView, contact

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
    path('contact/', contact, name="contact"),
]

patients/urls.py
from django.urls import path
from . import views

from django.conf import settings

urlpatterns = [
    #urls de pacientes
    path('patients/', views.PatientListView.as_view(), name='patients-list'),
    path('patients/create/', views.PatientCreateView.as_view(), name='patient-create'),
    path('patients/update/<int:pk>/', views.PatientUpdateView.as_view(), name='patient-update'),
    path('patients/delete/<int:pk>/', views.PatientDeleteView.as_view(), name='patient-delete'),
    path('patients/professional/<int:pk>/', views.PatientsOfProfessionalListView.as_view(), name='patients-professional-list'),

    #urls de compañia medica
    path('companies/', views.CompanyListView.as_view(), name='companies-list'),
    path('companies/create/', views.CompanyCreateView.as_view(), name='companies-create'),
    path('companies/update/<int:pk>/', views.CompanyUpdateView.as_view(), name='companies-update'),
    path('companies/delete/<int:pk>/', views.CompanyDeleteView.as_view(), name='companies-delete'),
]



# Ruta imagenes para que se muestren en el panel de administrador cuando estemos en desarrollo (settings.DEBUG == True)

if settings.DEBUG:
    from django.conf.urls.static import static
    # variables MEDIA_URL Y MEDIA_ROOT las tenemos que declarar en el settings del proyecto
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patients/models.py
from django.db import models
from professionals.models import Professional

# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nombre')

    class Meta:
        verbose_name = 'Compañía'
        verbose_name_plural = 'Compañías'
        ordering = ['name']
        
    
    def __str__(self):
        return self.name

class Patient(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nombre')
    surnames = models.CharField(max_length=100, verbose_name='Apellidos')
    company = models.ForeignKey(Company, verbose_name='Compañía Seguro', blank=True, null=True, on_delete=models.CASCADE)
    professional = models.ForeignKey(Professional, on_delete=models.CASCADE, verbose_name='Profesional')
    email = models.EmailField(verbose_name='Email', max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'
        ordering = ['name']
        
    
    def __str__(self):
        return '{} {}'.format(self.name.title(), self.surnames.title())
        

patients/forms.py
from django import forms
from .models import Patient, Company
from professionals.models import Professional

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Nombre'}),
            'surnames': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Apellidos'}),
            'company': forms.Select(attrs={'class':'form-control'}),
            'professional': forms.Select(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder': 'Email'})
            
        }
        labels = {
            'name':'', 
            'surnames':'',
            'company': 'Compañía Médica',
            'professional':'Profesional',
            'email': ''
        }

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Nombre'}),
            
        }
        labels = {
            'name':''
            
        }

patients/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from .models import Patient, Company
from .forms import PatientForm, CompanyForm
from professionals.models import Professional

# Create your views here.

@method_decorator(staff_member_required, name='dispatch')
class PatientListView(ListView):
    model = Patient
    template_name = 'patients/patients_list.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Pacientes'
        return context

@method_decorator(staff_member_required, name='dispatch')
class PatientCreateView(CreateView):
    model = Patient
    form_class = PatientForm
    template_name = 'patients/patient_form.html'
    success_url = reverse_lazy('patients-list')

# vista para editar un paciente
@method_decorator(staff_member_required, name='dispatch')
class PatientUpdateView(UpdateView):
    model = Patient
    form_class = PatientForm
    template_name = 'patients/patient_form.html'
    success_url = reverse_lazy('patients-list')

# vista para eliminar un paciente
@method_decorator(staff_member_required, name='dispatch')
class PatientDeleteView(DeleteView):
    model = Patient
    template_name = 'patients/patient_confirm_delete.html'
    success_url = reverse_lazy('patients-list')


# ------------- vistas para companies -------------
@method_decorator(staff_member_required, name='dispatch')
class CompanyListView(ListView):
    model = Company
    template_name = 'companies/company_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Compañías Médicas'
        return context
    
@method_decorator(staff_member_required, name='dispatch')
class CompanyCreateView(CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'companies/company_form.html'
    success_url = reverse_lazy('companies-list')

# vista para editar un paciente
@method_decorator(staff_member_required, name='dispatch')
class CompanyUpdateView(UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = 'companies/company_form.html'
    success_url = reverse_lazy('companies-list')

# vista para eliminar un paciente
@method_decorator(staff_member_required, name='dispatch')
class CompanyDeleteView(DeleteView):
    model = Company
    template_name = 'companies/company_confirm_delete.html'
    success_url = reverse_lazy('companies-list')

# vista para listar todos los pacientes que tiene un profesional
@method_decorator(staff_member_required, name='dispatch')
class PatientsOfProfessionalListView(ListView):
    model = Patient
    #template_name = 'patients/patients_professional_list.html'
    template_name = 'patients/patients_list.html'
    
    def get_queryset(self):
        self.professional_id = get_object_or_404(Professional, id=self.kwargs['pk'])
        print(self.professional_id)
        return Patient.objects.filter(professional=self.professional_id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Pacientes de {}'.format(Professional.objects.get(id=self.kwargs['pk'])) 
        return context
    

patients/templates/patients/patient_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Paciente{% endblock %}
{% block content %}
  <!-- Doctors Section -->
  
  <section id="doctors" class="doctors section">

    <!-- Section Title -->
    <div class="container section-title">
      <h1>Eliminar Paciente</h1>      
    </div><!-- End Section Title -->
    <div class="container">
      <div class="row gy-4">
        <form method="post">{% csrf_token %}
            <p>¿Seguro que quieres eliminar a <strong>{{object.name|title}} {{object.surnames|title}}</strong>?</p>
            
            <input type="submit" value="Confirmar" class="btn btn-success">
            <a href="{% url 'patients-list' %}" class="btn btn-danger" id="btn-delete-professional">Cancelar</a> 
        </form>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

patients/templates/patients/patient_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Pacientes{% endblock %}
{% block content %}
  <!-- Doctors Section -->
  
  <section id="doctors" class="doctors section">

    <!-- Section Title -->
    <div class="container section-title">
      {% if not object %}
        <h1>Crear Paciente</h1> 
      {% else %}
        <h1>Editar Paciente</h1>
      {% endif %}
    </div><!-- End Section Title -->
    <div class="container">
      <div class="row gy-4">
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <!-- Formulario -->
            <!--
            <input type="file" name="avatar" class="form-control-file mt-3" id="id_avatar">
            -->
            {{ form.as_p }}
            
            {% if not object %}
              <input type="submit" class="btn btn-primary btn-block mt-3" value="Crear">
            {% else %}
              <input type="submit" class="btn btn-primary btn-block mt-3" value="Actualizar">
            
            {% endif %}

            
            
        </form>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

patients/templates/patients/patients_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
  <!-- Doctors Section -->
  
  <section id="doctors" class="doctors section">

    <!-- Section Title -->
    <div class="container section-title">
      <h2>{{title}}</h2>
    </div><!-- End Section Title -->

    <div class="container text-center">
      <div class="row ">
        <div class="col">
            <a href="{% url 'patient-create' %}" class="btn btn-success" id="btn-update-professional">Crear Paciente</a>
        </div>
      </div>
    </div>

    <div class="container mt-5">
      <div class="row gy-4">
        <table class="table">
          <thead>
              <tr>
                <th scope="col">Nombre y Apellidos</th>
                <th scope="col">Compañia media</th>
                <th scope="col">Profesional</th>
                <th scope="col">Acción</th>
              </tr>
            </thead> 
            <tbody>
              {% for patient in patient_list %}
                  <tr>
                    <td>{{patient.name|title}} {{patient.surnames|title}}</td>
                    <td>{{patient.company}}</td>
                    <td>{{patient.professional}}</td>
                    <td>                      
                      <a href="{% url 'patient-update' patient.id %}" class="btn btn-primary" id="btn-update-professional">Editar</a>
                      <a href="{% url 'patient-delete' patient.id %}" class="btn btn-danger" id="btn-delete-professional">Eliminar</a>
                      <a href="{% url 'appointment-patient-list' patient.id %}" class="btn btn-secondary">Citas</a>  
                    </td>
                  </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}